### ISSUE TITLE
Entity 'vent speed' is missing

### ISSUE THREAD

**Issue by klaasjeha** [jeatheak/Mitsubishi-WF-RAC-Integration#131]
I can't change the vent speed from automatic, low to highest in the dashboard but the entity is missing. Only have horizontal and vertical swing direction entity available.

**Comment by c0mplex1** [comment]
To request the fan speed in an automation you could use this:
`
{{ state_attr('climate.<airco_name>', 'fan_mode') }}
`

To change the fan speed in an automation you could use this:
```
- action: climate.set_fan_mode
  data:
    fan_mode: <desired speed>
  target:
    entity_id: climate.<airco_name>
```
