### ISSUE TITLE
Use another entity as current temperature

### ISSUE THREAD

**Issue by Vitani** [jeatheak/Mitsubishi-WF-RAC-Integration#27]
I've found that the on-board thermometer can often times be very innacurate (both in the official app, and this add-on), for example my living room is "currently" 28.7 °C ... except there's no way that's true when I'm sat here cold wearing a jumper! I have another HA device in the same room which reads much more accurately (19.7 °C at present) and it'd be nice to be able to use that to drive the climate rather than the AC's own temperature. I believe I could set up a template climate device to do this myself, but that would be a PITA for one AC, let alone a house-full 😄

Don't know if it's possible, but I thought I'd ask!

**Comment by KixAss** [comment]
I've added a 'dual_smart_thermostat' for my airco's with a seperate temperature sensor and on- and off-switches:

```
switch:
  - platform: template
    switches:
      woonkamer_heater:
        value_template: "{{ is_state('climate.airco_woonkamer', 'heat') }}"
        turn_on:
          - service: climate.set_hvac_mode
            target:
              entity_id: climate.airco_woonkamer
            data:
              hvac_mode: 'heat'
          - service: climate.set_temperature
            target:
              entity_id: climate.airco_woonkamer
            data:
              temperature: 28
          - service: climate.set_fan_mode
            target:
              entity_id: climate.airco_woonkamer
            data:
              fan_mode: 'auto'

climate:
  - platform: dual_smart_thermostat
    name: Thermostaat Woonkamer
    heater: switch.woonkamer_heater
    cooler: switch.woonkamer_cooler
    target_sensor: sensor.woonkamer_temperature
    min_temp: 16
    max_temp: 25
    ac_mode: false
    target_temp: 21
    target_temp_high: 21.5
    target_temp_low: 20.5
    cold_tolerance: 0.5
    hot_tolerance: 0.5
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3
    initial_hvac_mode: "heat_cool"
    away_temp: 16
    precision: 0.1
```
