### ISSUE TITLE
climate into scene ->too many options copied into scenes.yaml

### ISSUE THREAD

**Issue by GittyBaer** [jeatheak/Mitsubishi-WF-RAC-Integration#43]
I think there is something wrong when adding an air conditioning unit into a scene with this integration?
It copies then all possible(!) options/states into the scene and not only the parameters the scene has to set.

Here is an example:
If I add one of my climate devices to a scene it looks like:
```
- id: '1675593892961'
  name: Test Scene
  entities:
    climate.klima_kueche:
      hvac_modes:
      - 'off'
      - auto
      - cool
      - dry
      - heat
      - fan_only
      min_temp: 16
      max_temp: 30
      fan_modes:
      - auto
      - 1 Lowest
      - 2 Low
      - 3 High
      - 4 Highest
      swing_modes:
      - Up/Down Auto
      - Highest
      - Middle
      - Normal
      - Lowest
      - 3D Auto
      current_temperature: 22.7
      temperature: 19
      fan_mode: 3 High
      swing_mode: Middle
      friendly_name: Klima-Kueche
      supported_features: 41
      state: heat
 ```

But I think this would be enough and what I would expect:
```
- id: '1675593892961'
  name: Test Scene
  entities:
    climate.klima_kueche:
      temperature: 19
      fan_mode: 3 High
      swing_mode: Middle
      friendly_name: Klima-Kueche  #<- here i'm not sure if it is necessary?
      state: heat
```

If I shorten my scenes.yaml to this it seems, that this is still working.

(Btw: Thank you so much for your great work and this integration!! 👍 :-) )
