### ISSUE TITLE
Climate: Add temperature change trough automation

### ISSUE THREAD

**Issue by nickdorrestein** [jeatheak/Mitsubishi-WF-RAC-Integration#69]
It would be cool if the temperature of the device can be changed trough automationy.

**Comment by jacekowski** [comment]
It already can be changed. You need to call climate.set_temperature service from your automation

```
action:
  - service: climate.set_temperature
    target:
      device_id: 82e0647cd436360378c6edcd3ea1df45
    data:
      temperature: 21

```
