### ISSUE TITLE
Add min/max temperature settings

### ISSUE THREAD

**Issue by jeatheak** [jeatheak/Mitsubishi-WF-RAC-Integration#7]
Add the method to set min/max temperature.
It is set to 7-35 according to the users

**Comment by jeatheak** [comment]
To change it manually in homeassistant you can change the entity with costumize:

For example: **/config/customize.yaml**
```yaml
climate.entity_id:
    max_temp: 28
    min_temp: 8
```
